/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hellw_testpjsip_Sip */

#ifndef _Included_com_hellw_testpjsip_Sip
#define _Included_com_hellw_testpjsip_Sip
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hellw_testpjsip_Sip
 * Method:    initSip
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hellw_testpjsip_Sip_initSip
  (JNIEnv *, jobject);

/*
 * Class:     com_hellw_testpjsip_Sip
 * Method:    regc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hellw_testpjsip_Sip_regc
  (JNIEnv *, jobject);

/*
 * Class:     com_hellw_testpjsip_Sip
 * Method:    destroySip
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hellw_testpjsip_Sip_destroySip
  (JNIEnv *, jobject);

/*
 * Class:     com_hellw_testpjsip_Sip
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hellw_testpjsip_Sip_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
